'use strict';

const { mkdir, readdir, readFile, rm, writeFile } = require('node:fs/promises');
const { join } = require('node:path');

/**
 * Make `@darts/*` resolvable in a packed app, without symlinks.
 *
 * The obvious implementation is a symlink (junction on Windows) from
 * `node_modules/@darts/x` to `packages/x`, and that is what this used to be.
 * It cannot work on Windows: the NSIS target archives the packed app with
 * 7z and unpacks it on the user's machine, and that round trip does not
 * preserve junctions -- each one comes back as a *copy* of the directory. A
 * copy is the one thing that must not happen, because Node refuses to strip
 * types from any file whose resolved path is inside node_modules
 * (ERR_UNSUPPORTED_NODE_MODULES_TYPE_STRIPPING), and the backend ships as
 * TypeScript. The installer built fine and then died on first launch.
 *
 * So instead of a link, each scope entry is a real, tiny package whose only
 * module re-exports the package's real entry point:
 *
 *   node_modules/@darts/engine/index.mjs
 *     export * from '../../../packages/engine/src/index.ts';
 *
 * That is what makes it robust: the restriction is on the path of the file
 * being stripped, not on who imported it. The shim itself is plain JavaScript
 * and needs no stripping; the specifier resolves to a real path under
 * `packages/`, which strips fine. And being ordinary files, there is nothing
 * for an archiver to dereference.
 *
 * Safe because every cross-package import is the bare specifier (each package
 * exports only `.`) and none of them has a default export, which `export *`
 * would not carry.
 */

/** Built assets, not an importable package. */
const NOT_A_PACKAGE = new Set(['frontend']);

async function relinkDartsPackages(appDir) {
  const packagesDir = join(appDir, 'packages');
  const scope = join(appDir, 'node_modules', '@darts');
  const done = [];

  await mkdir(scope, { recursive: true });

  for (const entry of await readdir(packagesDir, { withFileTypes: true })) {
    if (!entry.isDirectory() || NOT_A_PACKAGE.has(entry.name)) continue;

    const manifest = JSON.parse(await readFile(join(packagesDir, entry.name, 'package.json'), 'utf8'));
    const dir = join(scope, entry.name);

    // Whatever is there -- a pruned remnant, a workspace symlink npm made, an
    // earlier run's shim -- is replaced. `rm` unlinks a symlink rather than
    // following it, so this cannot reach into `packages/`.
    await rm(dir, { recursive: true, force: true });
    await mkdir(dir, { recursive: true });

    await writeFile(
      join(dir, 'package.json'),
      JSON.stringify(
        {
          name: manifest.name,
          version: manifest.version,
          private: true,
          type: 'module',
          exports: { '.': './index.mjs' },
        },
        null,
        2,
      ) + '\n',
    );
    await writeFile(
      join(dir, 'index.mjs'),
      `// Generated by scripts/package/relink.cjs -- see the comment there.\n` +
        `export * from '../../../packages/${entry.name}/src/index.ts';\n`,
    );

    done.push(entry.name);
  }

  return done;
}

module.exports = { relinkDartsPackages };
